name: Release
concurrency: build

on:
  push:
    tags:
    - "[0-9]+.[0-9]+.[0-9]+"

env:
    NETCORE_VERSION: '8.0.x'

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.NETCORE_VERSION }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the solution
      run: dotnet build EncryptedJson --configuration Release

    - name: Run tests
      run: dotnet test

  publish-to-nuget:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.NETCORE_VERSION }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Pack
      run: dotnet pack EncryptedJson -p:PackageVersion=${{ github.ref }}

    - name: Publish
      run: dotnet nuget push EncryptedJson/bin/Release/Xilabs.EncryptedJson.${{ github.ref }}.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
